#!/bin/sh

sed -i "s/^LIRCD_ARGS=.*/LIRCD_ARGS=\"--uinput\"/g" /etc/lirc/hardware.conf
sed -i "s/^DRIVER=.*/DRIVER=\"default\"/g" /etc/lirc/hardware.conf
sed -i "s/^DEVICE=.*/DEVICE=\"\/dev\/lirc0\"/g" /etc/lirc/hardware.conf
sed -i "s/^MODULES=.*/MODULES=\"gpio_ir_recv\"/g" /etc/lirc/hardware.conf

cat>/etc/lirc/lircd.odroid.conf<<__EOF
#
# Default remote controller for ODROID
#
# Copyright: 2015 Dongjin Kim <tobetter@gmail.com>
#
begin remote
	name	lircd.odroid.conf
	bits	16
	flags	SPACE_ENC | CONST_LENGTH
	eps	30
	aeps	100

	header		8964 4507
	one		544 1692
	zero		544 561
	ptrail		544
	pre_data_bits	16
	pre_data	0x4DB2
	gap		107872
	toggle_bit_mask	0x0

	begin codes
		KEY_LEFT	0x9966
		KEY_RIGHT	0x837C
		KEY_UP		0x53AC
		KEY_DOWN	0x4BB4
		KEY_ENTER	0x738C
		KEY_HOME	0x41BE
		KEY_MUTE	0x11EE
		KEY_MENU	0xA35C
		KEY_BACK	0x59A6
		KEY_VOLUMEDOWN	0x817E
		KEY_VOLUMEUP	0x01FE
		KEY_POWER	0x3BC4
	end codes
end remote
__EOF
